// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: proto/gokeymux.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RpcKeyService_KeyService_FullMethodName      = "/GoKeyMux.rpcKeyService/keyService"
	RpcKeyService_KeyServiceDebug_FullMethodName = "/GoKeyMux.rpcKeyService/keyServiceDebug"
)

// RpcKeyServiceClient is the client API for RpcKeyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RpcKeyServiceClient interface {
	KeyService(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[KeyInput, KeyReturn], error)
	KeyServiceDebug(ctx context.Context, in *KeyInputDebug, opts ...grpc.CallOption) (*KeyReturnDebug, error)
}

type rpcKeyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcKeyServiceClient(cc grpc.ClientConnInterface) RpcKeyServiceClient {
	return &rpcKeyServiceClient{cc}
}

func (c *rpcKeyServiceClient) KeyService(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[KeyInput, KeyReturn], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RpcKeyService_ServiceDesc.Streams[0], RpcKeyService_KeyService_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[KeyInput, KeyReturn]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RpcKeyService_KeyServiceClient = grpc.ClientStreamingClient[KeyInput, KeyReturn]

func (c *rpcKeyServiceClient) KeyServiceDebug(ctx context.Context, in *KeyInputDebug, opts ...grpc.CallOption) (*KeyReturnDebug, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyReturnDebug)
	err := c.cc.Invoke(ctx, RpcKeyService_KeyServiceDebug_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcKeyServiceServer is the server API for RpcKeyService service.
// All implementations must embed UnimplementedRpcKeyServiceServer
// for forward compatibility.
type RpcKeyServiceServer interface {
	KeyService(grpc.ClientStreamingServer[KeyInput, KeyReturn]) error
	KeyServiceDebug(context.Context, *KeyInputDebug) (*KeyReturnDebug, error)
	mustEmbedUnimplementedRpcKeyServiceServer()
}

// UnimplementedRpcKeyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRpcKeyServiceServer struct{}

func (UnimplementedRpcKeyServiceServer) KeyService(grpc.ClientStreamingServer[KeyInput, KeyReturn]) error {
	return status.Error(codes.Unimplemented, "method KeyService not implemented")
}
func (UnimplementedRpcKeyServiceServer) KeyServiceDebug(context.Context, *KeyInputDebug) (*KeyReturnDebug, error) {
	return nil, status.Error(codes.Unimplemented, "method KeyServiceDebug not implemented")
}
func (UnimplementedRpcKeyServiceServer) mustEmbedUnimplementedRpcKeyServiceServer() {}
func (UnimplementedRpcKeyServiceServer) testEmbeddedByValue()                       {}

// UnsafeRpcKeyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RpcKeyServiceServer will
// result in compilation errors.
type UnsafeRpcKeyServiceServer interface {
	mustEmbedUnimplementedRpcKeyServiceServer()
}

func RegisterRpcKeyServiceServer(s grpc.ServiceRegistrar, srv RpcKeyServiceServer) {
	// If the following call panics, it indicates UnimplementedRpcKeyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RpcKeyService_ServiceDesc, srv)
}

func _RpcKeyService_KeyService_Handler(srv any, stream grpc.ServerStream) error {
	return srv.(RpcKeyServiceServer).KeyService(&grpc.GenericServerStream[KeyInput, KeyReturn]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RpcKeyService_KeyServiceServer = grpc.ClientStreamingServer[KeyInput, KeyReturn]

func _RpcKeyService_KeyServiceDebug_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(KeyInputDebug)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcKeyServiceServer).KeyServiceDebug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcKeyService_KeyServiceDebug_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(RpcKeyServiceServer).KeyServiceDebug(ctx, req.(*KeyInputDebug))
	}
	return interceptor(ctx, in, info, handler)
}

// RpcKeyService_ServiceDesc is the grpc.ServiceDesc for RpcKeyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RpcKeyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GoKeyMux.rpcKeyService",
	HandlerType: (*RpcKeyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "keyServiceDebug",
			Handler:    _RpcKeyService_KeyServiceDebug_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "keyService",
			Handler:       _RpcKeyService_KeyService_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/gokeymux.proto",
}
